/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DaoCommodity;
import Model.HangDienMay;
import Model.HangThuCong;
import Model.IviewData;
import Model.MangHangHoa;
import java.awt.Event;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class HomeManagerJFrame extends javax.swing.JFrame implements IviewData{

    /**
     * Creates new form HomeManagerJFrame
     */
    MangHangHoa m ;
    List<Model.HangThuCong>listThuCongs;
    List<Model.HangDienMay>ListDienMays;
    DefaultTableModel modelDienmay;
    DefaultTableModel modelThuCong;
    public HomeManagerJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setRootPaneCheckingEnabled(rootPaneCheckingEnabled);
        modelDienmay =(DefaultTableModel) tblDienMay.getModel();
        modelThuCong=(DefaultTableModel) tblThuCong.getModel();
        MangHangHoa m = new MangHangHoa();
        ShowHandmade();
        ShowdataElectric();
        
    }
    public void ShowdataElectric(){
        this.ListDienMays=DaoCommodity.GetdataDienMays();
       this.showData(ListDienMays, modelDienmay);
    }
    public void ShowHandmade(){
        this.listThuCongs =DaoCommodity.getDataThucongs();
         this.showData(listThuCongs, modelThuCong);
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        Homelabel = new javax.swing.JLabel();
        paneThuCong = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblThuCong = new javax.swing.JTable();
        btnDeleteTC = new javax.swing.JButton();
        btnTimKiemTC = new javax.swing.JButton();
        btnThemTC = new javax.swing.JButton();
        btnBackTC = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDienMay = new javax.swing.JTable();
        btnThemDM = new javax.swing.JButton();
        btnTimKiemDM = new javax.swing.JButton();
        btnxoaDM = new javax.swing.JButton();
        BackDM = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("homeMainDesignHT");
        setForeground(new java.awt.Color(204, 204, 255));

        Homelabel.setBackground(new java.awt.Color(204, 204, 255));
        Homelabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Homelabel.setForeground(new java.awt.Color(204, 204, 255));
        Homelabel.setText("HOME COMMODITY MAIN");

        paneThuCong.setBackground(new java.awt.Color(51, 0, 51));
        paneThuCong.setForeground(new java.awt.Color(0, 153, 153));
        paneThuCong.setToolTipText("click để hiển thi thông tin hàng tiêu dùng");
        paneThuCong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblThuCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "ID", "Date", "Price", "Amount", "Producer"
            }
        ));
        jScrollPane4.setViewportView(tblThuCong);

        btnDeleteTC.setBackground(new java.awt.Color(204, 204, 255));
        btnDeleteTC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteTC.setForeground(new java.awt.Color(255, 51, 51));
        btnDeleteTC.setText("Xóa Bỏ");
        btnDeleteTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTCActionPerformed(evt);
            }
        });

        btnTimKiemTC.setBackground(new java.awt.Color(204, 204, 255));
        btnTimKiemTC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTimKiemTC.setForeground(new java.awt.Color(255, 51, 51));
        btnTimKiemTC.setText("Tìm Kiếm");
        btnTimKiemTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemTCActionPerformed(evt);
            }
        });

        btnThemTC.setBackground(new java.awt.Color(204, 204, 255));
        btnThemTC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemTC.setForeground(new java.awt.Color(255, 51, 51));
        btnThemTC.setText("Thêm Mới");
        btnThemTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTCActionPerformed(evt);
            }
        });

        btnBackTC.setBackground(new java.awt.Color(204, 204, 255));
        btnBackTC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBackTC.setForeground(new java.awt.Color(255, 51, 51));
        btnBackTC.setText("Trở lại");
        btnBackTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackTCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThemTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBackTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTimKiemTC))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemTC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiemTC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteTC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBackTC)
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneThuCong.addTab("QLHangThuCong", jPanel2);

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblDienMay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "ID", "Date", "Price", "Amount", "lLocaltion"
            }
        ));
        jScrollPane2.setViewportView(tblDienMay);

        btnThemDM.setBackground(new java.awt.Color(0, 51, 255));
        btnThemDM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemDM.setForeground(new java.awt.Color(255, 51, 51));
        btnThemDM.setText("Thêm mới");
        btnThemDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDMActionPerformed(evt);
            }
        });

        btnTimKiemDM.setBackground(new java.awt.Color(0, 51, 255));
        btnTimKiemDM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTimKiemDM.setForeground(new java.awt.Color(255, 51, 51));
        btnTimKiemDM.setText("Tìm kiếm");
        btnTimKiemDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemDMActionPerformed(evt);
            }
        });

        btnxoaDM.setBackground(new java.awt.Color(0, 51, 255));
        btnxoaDM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnxoaDM.setForeground(new java.awt.Color(255, 51, 51));
        btnxoaDM.setText("Xóa bỏ");

        BackDM.setBackground(new java.awt.Color(0, 51, 255));
        BackDM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BackDM.setForeground(new java.awt.Color(255, 51, 51));
        BackDM.setText("Trở lại");
        BackDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackDMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnxoaDM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemDM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BackDM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimKiemDM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemDM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiemDM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnxoaDM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BackDM)
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneThuCong.addTab("QLHangDienMay", jPanel1);

        jMenu1.setText("File       ");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("jMenuItem4");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        jMenu3.setText("HienThi      ");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");
        jMenu3.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");
        jMenu3.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");
        jMenu3.add(jCheckBoxMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Trợ Giúp");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");
        jMenu6.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");
        jMenu6.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");
        jMenu6.add(jRadioButtonMenuItem3);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(Homelabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(paneThuCong)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Homelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneThuCong, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackTCActionPerformed
        // TODO add your handling code here:
        ShowHandmade();
    }//GEN-LAST:event_btnBackTCActionPerformed

    private void btnThemTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTCActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnThemTCActionPerformed

    private void btnTimKiemTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemTCActionPerformed
        // TODO add your handling code here:
       String find = JOptionPane.showInputDialog("Nhap vao ID Hang Thu Cong can tim kiem");
       if(find != null& find.length()>0){
           listThuCongs =DaoCommodity.findByID(find);
           if(listThuCongs.size()==0) {
                JOptionPane.showMessageDialog(this, "khong tim thay  gi");
           }
           showData(listThuCongs, modelThuCong);
       }else {
           ShowHandmade();
       }
        
    }//GEN-LAST:event_btnTimKiemTCActionPerformed

    private void btnThemDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemDMActionPerformed

    private void btnTimKiemDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemDMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemDMActionPerformed

    private void BackDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackDMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackDMActionPerformed

    private void btnDeleteTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTCActionPerformed
        // TODO add your handling code here:
        int local =tblThuCong.getSelectedRow();
        if(listThuCongs.size()==0){
            JOptionPane.showMessageDialog(this, "khong con gi de xoa");
        }
        if(local ==-1){
            JOptionPane.showMessageDialog(this, "vui long chon hang chua item de xoa");
        }
        else {
             int choose = JOptionPane.showConfirmDialog(this,  "ban co muon xoa item nay khong");
        if(choose == JOptionPane.YES_OPTION){
            listThuCongs.remove(local);
            showData(listThuCongs, modelThuCong);
        }
        }
       
        
    }//GEN-LAST:event_btnDeleteTCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeManagerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackDM;
    private javax.swing.JLabel Homelabel;
    private javax.swing.JButton btnBackTC;
    private javax.swing.JButton btnDeleteTC;
    private javax.swing.JButton btnThemDM;
    private javax.swing.JButton btnThemTC;
    private javax.swing.JButton btnTimKiemDM;
    private javax.swing.JButton btnTimKiemTC;
    private javax.swing.JButton btnxoaDM;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane paneThuCong;
    private javax.swing.JTable tblDienMay;
    private javax.swing.JTable tblThuCong;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void showData(List<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        for (T t : list) {
           if(t instanceof HangDienMay){
               HangDienMay l = (HangDienMay) t;
               model.addRow(new Object[]{
                   model.getRowCount()+1,l.getCommodityID(),l.getInputdate()
                   ,l.getPrice(),l.getAmount(),l.getLocaltion()
               });
           }
            if(t instanceof HangThuCong){
               HangThuCong l = (HangThuCong) t;
               model.addRow(new Object[]{
                   model.getRowCount()+1,l.getCommodityID(),l.getInputdate()
                   ,l.getPrice(),l.getAmount(),l.getProducer()
               });
           }
        }
    }
}
